name: 'Create Main Merge PR'
on:
    push:
        branches:
            - development

jobs:
    create-pr-on-push:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@1.0.0

            - name: Create pull request
              uses: thomaseizinger/create-pull-request@master
              with:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  head: ${{ github.ref }}
                  base: main
                  title: 'Main Merge'
